<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('appointment_data', function (Blueprint $table) {
            //
            // $table->string('rhu_xray_result', 10)->default(null)->nullable();
            // $table->string('rhu_xray_remarks', 10)->default(null)->nullable();
            $table->string('ankle_apl_apo', 10)->default(null)->nullable();
            $table->string('ankle_apl_apo_pf', 10)->default(null)->nullable();
            $table->string('ankle_mortisse_view_right_pf', 10)->default(null)->nullable();
            $table->string('ankle_both_apl_pf', 10)->default(null)->nullable();
            $table->string('arm_apl_right', 10)->default(null)->nullable();
            $table->string('axillary_view_pf', 10)->default(null)->nullable();
            $table->string('calcaneus_lateral_view', 10)->default(null)->nullable();
            $table->string('calcaneus_pf', 10)->default(null)->nullable();
            $table->string('cervical_apl_obliques', 10)->default(null)->nullable();
            $table->string('cervical_apl_obliques_pf', 10)->default(null)->nullable();
            $table->string('cervical_apl_pf', 10)->default(null)->nullable();
            $table->string('cervical_apo', 10)->default(null)->nullable();
            $table->string('cervicothoracic_spine_apl', 10)->default(null)->nullable();
            $table->string('chest_ap_pf', 10)->default(null)->nullable();
            $table->string('chest_apl_pf', 10)->default(null)->nullable();
            $table->string('chest_cone_down_view_pf', 10)->default(null)->nullable();
            $table->string('chest_lateral_view_only_pf', 10)->default(null)->nullable();
            $table->string('chest_pa_pf', 10)->default(null)->nullable();
            $table->string('chest_pal_pf', 10)->default(null)->nullable();
            $table->string('chest_rpo', 10)->default(null)->nullable();
            $table->string('chest_spot_view_left_upper_lf', 10)->default(null)->nullable();
            $table->string('chest_spot_view_left_upper_lf_pf', 10)->default(null)->nullable();
            $table->string('chest_spot_view_right_lower_lf', 10)->default(null)->nullable();
            $table->string('chest_spot_view_right_lower_lf_pf', 10)->default(null)->nullable();
            $table->string('chest_spot_view_right_ulf', 10)->default(null)->nullable();
            $table->string('chest_spot_view_right_ulf_pf', 10)->default(null)->nullable();
            $table->string('clavicle_ap_with_cephalic_tilt_pf', 10)->default(null)->nullable();
            $table->string('clavicle_r_and_l_pf', 10)->default(null)->nullable();
            $table->string('coccyx_ap_pf', 10)->default(null)->nullable();
            $table->string('coccyx_apl_pf', 10)->default(null)->nullable();
            $table->string('digit_apl_apo_pf', 10)->default(null)->nullable();
            $table->string('elbow_both_apl_pf', 10)->default(null)->nullable();
            $table->string('foot_ap_pf', 10)->default(null)->nullable();
            $table->string('foot_apl_bilateral', 10)->default(null)->nullable();
            $table->string('foot_apl_bilateral_pf', 10)->default(null)->nullable();
            $table->string('foot_apl_left', 10)->default(null)->nullable();
            $table->string('foot_apl_left_pf', 10)->default(null)->nullable();
            $table->string('foot_apo_left', 10)->default(null)->nullable();
            $table->string('foot_apo_left_pf', 10)->default(null)->nullable();
            $table->string('foot_apo_right', 10)->default(null)->nullable();
            $table->string('foot_apo_right_pf', 10)->default(null)->nullable();
            $table->string('foot_apl_both', 10)->default(null)->nullable();
            $table->string('foot_lateral_view_right', 10)->default(null)->nullable();
            $table->string('foot_lateral_view_right_pf', 10)->default(null)->nullable();
            $table->string('forearm_both_apl_pf', 10)->default(null)->nullable();
            $table->string('hand_apl_right_pf', 10)->default(null)->nullable();
            $table->string('hand_apo_left', 10)->default(null)->nullable();
            $table->string('hand_lateral_view_right', 10)->default(null)->nullable();
            $table->string('hand_lateral_view_right_pf', 10)->default(null)->nullable();
            $table->string('hand_left_bone_aging', 10)->default(null)->nullable();
            $table->string('hand_left_bone_aging_pf', 10)->default(null)->nullable();
            $table->string('hard_copy_image_xray', 10)->default(null)->nullable();
            $table->string('hip_ap_ct_apl', 10)->default(null)->nullable();
            $table->string('hip_ap_ct_apl_pf', 10)->default(null)->nullable();
            $table->string('humerus_ap', 10)->default(null)->nullable();
            $table->string('humerus_both_apl_pf', 10)->default(null)->nullable();
            $table->string('intraop_x_3_shots', 10)->default(null)->nullable();
            $table->string('intraop_x_4_shots', 10)->default(null)->nullable();
            $table->string('ivp_x_2_shots', 10)->default(null)->nullable();
            $table->string('ivp_x_3_shots', 10)->default(null)->nullable();
            $table->string('ivp_x_5_shots', 10)->default(null)->nullable();
            $table->string('ivp_x_6_shots', 10)->default(null)->nullable();
            $table->string('ivp_x_7_shots', 10)->default(null)->nullable();
            $table->string('ivp_x_8_shots', 10)->default(null)->nullable();
            $table->string('judet_view_left_hip_joint', 10)->default(null)->nullable();
            $table->string('judet_view_left_hip_joint_pf', 10)->default(null)->nullable();
            $table->string('judet_view_right_hip_joint_pf', 10)->default(null)->nullable();
            $table->string('knee_apl_left', 10)->default(null)->nullable();
            $table->string('knee_apl_left_pf', 10)->default(null)->nullable();
            $table->string('knee_tunnel_view_right', 10)->default(null)->nullable();
            $table->string('knee_tunnel_view_left_pf', 10)->default(null)->nullable();
            $table->string('knees_both_apl', 10)->default(null)->nullable();
            $table->string('knees_both_apl_pf', 10)->default(null)->nullable();
            $table->string('kub_xray_pf', 10)->default(null)->nullable();
            $table->string('leg_apl_right', 10)->default(null)->nullable();
            $table->string('leg_apl_pf', 10)->default(null)->nullable();
            $table->string('lumbar_apl_pf', 10)->default(null)->nullable();
            $table->string('lumbosacral_ls_oblique', 10)->default(null)->nullable();
            $table->string('lumbosacral_ls_oblique_pf', 10)->default(null)->nullable();
            $table->string('lumbosacral_spine_apl_oblique_pf', 10)->default(null)->nullable();
            $table->string('lumbosacral_spine_apl_pf', 10)->default(null)->nullable();
            $table->string('mandible_apo_pf', 10)->default(null)->nullable();
            $table->string('mastoid_series', 10)->default(null)->nullable();
            $table->string('mastoid_series_pf', 10)->default(null)->nullable();
            $table->string('nasal_bone_pf', 10)->default(null)->nullable();
            $table->string('orbit_caldwell_pf', 10)->default(null)->nullable();
            $table->string('orbit_water_and_caldwell_pf', 10)->default(null)->nullable();
            $table->string('os_calcis_view_pf', 10)->default(null)->nullable();
            $table->string('paranasal_sinuses_pf', 10)->default(null)->nullable();
            $table->string('pelvis_ap_pf', 10)->default(null)->nullable();
            $table->string('pelvis_apl_pf', 10)->default(null)->nullable();
            $table->string('rgp_x_1_shot', 10)->default(null)->nullable();
            $table->string('rgp_x_2_shot', 10)->default(null)->nullable();
            $table->string('rgp_x_3_shot', 10)->default(null)->nullable();
            $table->string('rgp_x_4_shot', 10)->default(null)->nullable();
            $table->string('rgp_x_5_shot', 10)->default(null)->nullable();
            $table->string('scapula_lat_pf', 10)->default(null)->nullable();
            $table->string('scoliosis_series', 10)->default(null)->nullable();
            $table->string('scoliosis_series_pf', 10)->default(null)->nullable();
            $table->string('second_copy_of_result_opd_only', 10)->default(null)->nullable();
            $table->string('shoulder_ap_l_pf', 10)->default(null)->nullable();
            $table->string('shoulder_ap_r_pf', 10)->default(null)->nullable();
            $table->string('shoulder_apo_r_pf', 10)->default(null)->nullable();
            $table->string('skull_ap_pf', 10)->default(null)->nullable();
            $table->string('skull_lateral_view_pf', 10)->default(null)->nullable();
            $table->string('skull_series_apl_townes_views_pf', 10)->default(null)->nullable();
            $table->string('skull_submentovertex_pf', 10)->default(null)->nullable();
            $table->string('skull_waters_view_pf', 10)->default(null)->nullable();
            $table->string('tbc_apl', 10)->default(null)->nullable();
            $table->string('tbc_with_obliques', 10)->default(null)->nullable();
            $table->string('temporo_mandibular_joint_pf', 10)->default(null)->nullable();
            $table->string('thoracic_bony_cage_ap_pf', 10)->default(null)->nullable();
            $table->string('thoracic_bony_cage_apl_pf', 10)->default(null)->nullable();
            $table->string('thoracic_bony_cage_r_l_oblique_pf', 10)->default(null)->nullable();
            $table->string('thoracic_bony_cage_with_obliques_pf', 10)->default(null)->nullable();
            $table->string('thoraco_bony_cage_tbc_with_obliques', 10)->default(null)->nullable();
            $table->string('thoracolumbar_ap', 10)->default(null)->nullable();
            $table->string('thoracolumbar_apl', 10)->default(null)->nullable();
            $table->string('tibial_plateau_both_obliques', 10)->default(null)->nullable();
            $table->string('wrist_apl_left', 10)->default(null)->nullable();
            $table->string('wrist_apo_left', 10)->default(null)->nullable();
            $table->string('wrist_apo_right', 10)->default(null)->nullable();
            $table->string('wrist_apo_pf', 10)->default(null)->nullable();
            $table->string('wrist_both_apl', 10)->default(null)->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('appointment_data', function (Blueprint $table) {
            //
            // $table->dropColumn('rhu_xray_result');
            // $table->dropColumn('rhu_xray_remarks');
            $table->dropColumn('ankle_apl_apo');
            $table->dropColumn('ankle_apl_apo_pf');
            $table->dropColumn('ankle_mortisse_view_right_pf');
            $table->dropColumn('ankle_both_apl_pf');
            $table->dropColumn('arm_apl_right');
            $table->dropColumn('axillary_view_pf');
            $table->dropColumn('calcaneus_lateral_view');
            $table->dropColumn('calcaneus_pf');
            $table->dropColumn('cervical_apl_obliques');
            $table->dropColumn('cervical_apl_obliques_pf');
            $table->dropColumn('cervical_apl_pf');
            $table->dropColumn('cervical_apo');
            $table->dropColumn('cervicothoracic_spine_apl');
            $table->dropColumn('chest_ap_pf');
            $table->dropColumn('chest_apl_pf');
            $table->dropColumn('chest_cone_down_view_pf');
            $table->dropColumn('chest_lateral_view_only_pf');
            $table->dropColumn('chest_pa_pf');
            $table->dropColumn('chest_pal_pf');
            $table->dropColumn('chest_rpo');
            $table->dropColumn('chest_spot_view_left_upper_lf');
            $table->dropColumn('chest_spot_view_left_upper_lf_pf');
            $table->dropColumn('chest_spot_view_right_lower_lf');
            $table->dropColumn('chest_spot_view_right_lower_lf_pf');
            $table->dropColumn('chest_spot_view_right_ulf');
            $table->dropColumn('chest_spot_view_right_ulf_pf');
            $table->dropColumn('clavicle_ap_with_cephalic_tilt_pf');
            $table->dropColumn('clavicle_r_and_l_pf');
            $table->dropColumn('coccyx_ap_pf');
            $table->dropColumn('coccyx_apl_pf');
            $table->dropColumn('digit_apl_apo_pf');
            $table->dropColumn('elbow_both_apl_pf');
            $table->dropColumn('foot_ap_pf');
            $table->dropColumn('foot_apl_bilateral');
            $table->dropColumn('foot_apl_bilateral_pf');
            $table->dropColumn('foot_apl_left');
            $table->dropColumn('foot_apl_left_pf');
            $table->dropColumn('foot_apo_left');
            $table->dropColumn('foot_apo_left_pf');
            $table->dropColumn('foot_apo_right');
            $table->dropColumn('foot_apo_right_pf');
            $table->dropColumn('foot_apl_both');
            $table->dropColumn('foot_lateral_view_right');
            $table->dropColumn('foot_lateral_view_right_pf');
            $table->dropColumn('forearm_both_apl_pf');
            $table->dropColumn('hand_apl_right_pf');
            $table->dropColumn('hand_apo_left');
            $table->dropColumn('hand_lateral_view_right');
            $table->dropColumn('hand_lateral_view_right_pf');
            $table->dropColumn('hand_left_bone_aging');
            $table->dropColumn('hand_left_bone_aging_pf');
            $table->dropColumn('hard_copy_image_xray');
            $table->dropColumn('hip_ap_ct_apl');
            $table->dropColumn('hip_ap_ct_apl_pf');
            $table->dropColumn('humerus_ap');
            $table->dropColumn('humerus_both_apl_pf');
            $table->dropColumn('intraop_x_3_shots');
            $table->dropColumn('intraop_x_4_shots');
            $table->dropColumn('ivp_x_2_shots');
            $table->dropColumn('ivp_x_3_shots');
            $table->dropColumn('ivp_x_5_shots');
            $table->dropColumn('ivp_x_6_shots');
            $table->dropColumn('ivp_x_7_shots');
            $table->dropColumn('ivp_x_8_shots');
            $table->dropColumn('judet_view_left_hip_joint');
            $table->dropColumn('judet_view_left_hip_joint_pf');
            $table->dropColumn('judet_view_right_hip_joint_pf');
            $table->dropColumn('knee_apl_left');
            $table->dropColumn('knee_apl_left_pf');
            $table->dropColumn('knee_tunnel_view_right');
            $table->dropColumn('knee_tunnel_view_left_pf');
            $table->dropColumn('knees_both_apl');
            $table->dropColumn('knees_both_apl_pf');
            $table->dropColumn('kub_xray_pf');
            $table->dropColumn('leg_apl_right');
            $table->dropColumn('leg_apl_pf');
            $table->dropColumn('lumbar_apl_pf');
            $table->dropColumn('lumbosacral_ls_oblique');
            $table->dropColumn('lumbosacral_ls_oblique_pf');
            $table->dropColumn('lumbosacral_spine_apl_oblique_pf');
            $table->dropColumn('lumbosacral_spine_apl_pf');
            $table->dropColumn('mandible_apo_pf');
            $table->dropColumn('mastoid_series');
            $table->dropColumn('mastoid_series_pf');
            $table->dropColumn('nasal_bone_pf');
            $table->dropColumn('orbit_caldwell_pf');
            $table->dropColumn('orbit_water_and_caldwell_pf');
            $table->dropColumn('os_calcis_view_pf');
            $table->dropColumn('paranasal_sinuses_pf');
            $table->dropColumn('pelvis_ap_pf');
            $table->dropColumn('pelvis_apl_pf');
            $table->dropColumn('rgp_x_1_shot');
            $table->dropColumn('rgp_x_2_shot');
            $table->dropColumn('rgp_x_3_shot');
            $table->dropColumn('rgp_x_4_shot');
            $table->dropColumn('rgp_x_5_shot');
            $table->dropColumn('scapula_lat_pf');
            $table->dropColumn('scoliosis_series');
            $table->dropColumn('scoliosis_series_pf');
            $table->dropColumn('second_copy_of_result_opd_only');
            $table->dropColumn('shoulder_ap_l_pf');
            $table->dropColumn('shoulder_ap_r_pf');
            $table->dropColumn('shoulder_apo_r_pf');
            $table->dropColumn('skull_ap_pf');
            $table->dropColumn('skull_lateral_view_pf');
            $table->dropColumn('skull_series_apl_townes_views_pf');
            $table->dropColumn('skull_submentovertex_pf');
            $table->dropColumn('skull_waters_view_pf');
            $table->dropColumn('tbc_apl');
            $table->dropColumn('tbc_with_obliques');
            $table->dropColumn('temporo_mandibular_joint_pf');
            $table->dropColumn('thoracic_bony_cage_ap_pf');
            $table->dropColumn('thoracic_bony_cage_apl_pf');
            $table->dropColumn('thoracic_bony_cage_r_l_oblique_pf');
            $table->dropColumn('thoracic_bony_cage_with_obliques_pf');
            $table->dropColumn('thoraco_bony_cage_tbc_with_obliques');
            $table->dropColumn('thoracolumbar_ap');
            $table->dropColumn('thoracolumbar_apl');
            $table->dropColumn('tibial_plateau_both_obliques');
            $table->dropColumn('wrist_apl_left');
            $table->dropColumn('wrist_apo_left');
            $table->dropColumn('wrist_apo_right');
            $table->dropColumn('wrist_apo_pf');
            $table->dropColumn('wrist_both_apl');
        });
    }
};
