<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;
class _Laboratory_microscopy extends Model
{ 
    public static function laboratory_microscopy(){ 
        // syncronize laboratory_microscopy table from offline to online   
        $lab_offline = DB::table('laboratory_microscopy')->get();  
        foreach($lab_offline as $lab_offline){  
            $lab_offline_count = DB::connection('mysql2')->table('laboratory_microscopy')->where('lm_id', $lab_offline->lm_id)->get();
                if(count($lab_offline_count) > 0){ 
                    if($lab_offline->updated_at > $lab_offline_count[0]->updated_at){  
                        DB::connection('mysql2')->table('laboratory_microscopy')->where('lm_id', $lab_offline->lm_id)->update([    
                            'lm_id'=> $lab_offline->lm_id, 
                            'order_id'=>$lab_offline->order_id,
                            'doctor_id'=>$lab_offline->doctor_id,
                            'patient_id'=>$lab_offline->patient_id,
                            'laboratory_id'=>$lab_offline->laboratory_id,
                            'is_viewed'=>$lab_offline->is_viewed,
                            'is_processed'=>$lab_offline->is_processed,
                            'is_processed_by'=>$lab_offline->is_processed_by,
                            'is_processed_time_start'=>$lab_offline->is_processed_time_start,
                            'is_processed_time_end'=>$lab_offline->is_processed_time_end,
                            'is_pending'=>$lab_offline->is_pending,
                            'is_pending_reason'=>$lab_offline->is_pending_reason,
                            'is_pending_date'=>$lab_offline->is_pending_date,
                            'is_pending_by'=>$lab_offline->is_pending_by,
                            'spicemen'=>$lab_offline->spicemen,
                            'chemical_test'=>$lab_offline->chemical_test,
                            'chemical_test_color'=>$lab_offline->chemical_test_color,
                            'chemical_test_transparency'=>$lab_offline->chemical_test_transparency,
                            'chemical_test_ph'=>$lab_offline->chemical_test_ph,
                            'chemical_test_spicific_gravity'=>$lab_offline->chemical_test_spicific_gravity,
                            'chemical_test_glucose'=>$lab_offline->chemical_test_glucose,
                            'chemical_test_albumin'=>$lab_offline->chemical_test_albumin,
                            'microscopic_test'=>$lab_offline->microscopic_test,
                            'microscopic_test_squamous'=>$lab_offline->microscopic_test_squamous,
                            'microscopic_test_pus'=>$lab_offline->microscopic_test_pus,
                            'microscopic_test_redblood'=>$lab_offline->microscopic_test_redblood,
                            'microscopic_test_hyaline'=>$lab_offline->microscopic_test_hyaline,
                            'microscopic_test_wbc'=>$lab_offline->microscopic_test_wbc,
                            'microscopic_test_rbc'=>$lab_offline->microscopic_test_rbc,
                            'microscopic_test_fine_granular'=>$lab_offline->microscopic_test_fine_granular,
                            'microscopic_test_coarse_granular'=>$lab_offline->microscopic_test_coarse_granular,
                            'microscopic_test_calcium_oxalate'=>$lab_offline->microscopic_test_calcium_oxalate,
                            'microscopic_test_triple_phospahte'=>$lab_offline->microscopic_test_triple_phospahte,
                            'microscopic_test_leucine_tyrosine'=>$lab_offline->microscopic_test_leucine_tyrosine,
                            'microscopic_test_ammonium_biurate'=>$lab_offline->microscopic_test_ammonium_biurate,
                            'microscopic_test_amorphous_urates'=>$lab_offline->microscopic_test_amorphous_urates,
                            'microscopic_test_amorphous_phosphates'=>$lab_offline->microscopic_test_amorphous_phosphates,
                            'microscopic_test_uricacid'=>$lab_offline->microscopic_test_uricacid,
                            'microscopic_test_mucus_thread'=>$lab_offline->microscopic_test_mucus_thread,
                            'microscopic_test_bacteria'=>$lab_offline->microscopic_test_bacteria,
                            'microscopic_test_yeast'=>$lab_offline->microscopic_test_yeast,
                            'pregnancy_test_hcg'=>$lab_offline->pregnancy_test_hcg,
                            'pregnancy_test_hcg_result'=>$lab_offline->pregnancy_test_hcg_result,
                            'order_status'=>$lab_offline->order_status,
                            'order_remarks'=>$lab_offline->order_remarks,
                            'result_remarks'=>$lab_offline->result_remarks,
                            'status'=>$lab_offline->status,
                            'created_at'=>$lab_offline->created_at,
                            'updated_at'=>$lab_offline->updated_at
                        ]);
                    } 
                    else{
                        DB::table('laboratory_microscopy')->where('lm_id', $lab_offline_count[0]->lm_id)->update([  
                            'lm_id'=> $lab_offline_count[0]->lm_id, 
                            'order_id'=>$lab_offline_count[0]->order_id,
                            'doctor_id'=>$lab_offline_count[0]->doctor_id,
                            'patient_id'=>$lab_offline_count[0]->patient_id,
                            'laboratory_id'=>$lab_offline_count[0]->laboratory_id,
                            'is_viewed'=>$lab_offline_count[0]->is_viewed,
                            'is_processed'=>$lab_offline_count[0]->is_processed,
                            'is_processed_by'=>$lab_offline_count[0]->is_processed_by,
                            'is_processed_time_start'=>$lab_offline_count[0]->is_processed_time_start,
                            'is_processed_time_end'=>$lab_offline_count[0]->is_processed_time_end,
                            'is_pending'=>$lab_offline_count[0]->is_pending,
                            'is_pending_reason'=>$lab_offline_count[0]->is_pending_reason,
                            'is_pending_date'=>$lab_offline_count[0]->is_pending_date,
                            'is_pending_by'=>$lab_offline_count[0]->is_pending_by,
                            'spicemen'=>$lab_offline_count[0]->spicemen,
                            'chemical_test'=>$lab_offline_count[0]->chemical_test,
                            'chemical_test_color'=>$lab_offline_count[0]->chemical_test_color,
                            'chemical_test_transparency'=>$lab_offline_count[0]->chemical_test_transparency,
                            'chemical_test_ph'=>$lab_offline_count[0]->chemical_test_ph,
                            'chemical_test_spicific_gravity'=>$lab_offline_count[0]->chemical_test_spicific_gravity,
                            'chemical_test_glucose'=>$lab_offline_count[0]->chemical_test_glucose,
                            'chemical_test_albumin'=>$lab_offline_count[0]->chemical_test_albumin,
                            'microscopic_test'=>$lab_offline_count[0]->microscopic_test,
                            'microscopic_test_squamous'=>$lab_offline_count[0]->microscopic_test_squamous,
                            'microscopic_test_pus'=>$lab_offline_count[0]->microscopic_test_pus,
                            'microscopic_test_redblood'=>$lab_offline_count[0]->microscopic_test_redblood,
                            'microscopic_test_hyaline'=>$lab_offline_count[0]->microscopic_test_hyaline,
                            'microscopic_test_wbc'=>$lab_offline_count[0]->microscopic_test_wbc,
                            'microscopic_test_rbc'=>$lab_offline_count[0]->microscopic_test_rbc,
                            'microscopic_test_fine_granular'=>$lab_offline_count[0]->microscopic_test_fine_granular,
                            'microscopic_test_coarse_granular'=>$lab_offline_count[0]->microscopic_test_coarse_granular,
                            'microscopic_test_calcium_oxalate'=>$lab_offline_count[0]->microscopic_test_calcium_oxalate,
                            'microscopic_test_triple_phospahte'=>$lab_offline_count[0]->microscopic_test_triple_phospahte,
                            'microscopic_test_leucine_tyrosine'=>$lab_offline_count[0]->microscopic_test_leucine_tyrosine,
                            'microscopic_test_ammonium_biurate'=>$lab_offline_count[0]->microscopic_test_ammonium_biurate,
                            'microscopic_test_amorphous_urates'=>$lab_offline_count[0]->microscopic_test_amorphous_urates,
                            'microscopic_test_amorphous_phosphates'=>$lab_offline_count[0]->microscopic_test_amorphous_phosphates,
                            'microscopic_test_uricacid'=>$lab_offline_count[0]->microscopic_test_uricacid,
                            'microscopic_test_mucus_thread'=>$lab_offline_count[0]->microscopic_test_mucus_thread,
                            'microscopic_test_bacteria'=>$lab_offline_count[0]->microscopic_test_bacteria,
                            'microscopic_test_yeast'=>$lab_offline_count[0]->microscopic_test_yeast,
                            'pregnancy_test_hcg'=>$lab_offline_count[0]->pregnancy_test_hcg,
                            'pregnancy_test_hcg_result'=>$lab_offline_count[0]->pregnancy_test_hcg_result,
                            'order_status'=>$lab_offline_count[0]->order_status,
                            'order_remarks'=>$lab_offline_count[0]->order_remarks,
                            'result_remarks'=>$lab_offline_count[0]->result_remarks,
                            'status'=>$lab_offline_count[0]->status,
                            'created_at'=>$lab_offline_count[0]->created_at,
                            'updated_at'=>$lab_offline_count[0]->updated_at
                        ]);
                    }  
                }else{
                    DB::connection('mysql2')->table('laboratory_microscopy')->insert([ 
                        'lm_id'=> $lab_offline->lm_id, 
                        'order_id'=>$lab_offline->order_id,
                        'doctor_id'=>$lab_offline->doctor_id,
                        'patient_id'=>$lab_offline->patient_id,
                        'laboratory_id'=>$lab_offline->laboratory_id,
                        'is_viewed'=>$lab_offline->is_viewed,
                        'is_processed'=>$lab_offline->is_processed,
                        'is_processed_by'=>$lab_offline->is_processed_by,
                        'is_processed_time_start'=>$lab_offline->is_processed_time_start,
                        'is_processed_time_end'=>$lab_offline->is_processed_time_end,
                        'is_pending'=>$lab_offline->is_pending,
                        'is_pending_reason'=>$lab_offline->is_pending_reason,
                        'is_pending_date'=>$lab_offline->is_pending_date,
                        'is_pending_by'=>$lab_offline->is_pending_by,
                        'spicemen'=>$lab_offline->spicemen,
                        'chemical_test'=>$lab_offline->chemical_test,
                        'chemical_test_color'=>$lab_offline->chemical_test_color,
                        'chemical_test_transparency'=>$lab_offline->chemical_test_transparency,
                        'chemical_test_ph'=>$lab_offline->chemical_test_ph,
                        'chemical_test_spicific_gravity'=>$lab_offline->chemical_test_spicific_gravity,
                        'chemical_test_glucose'=>$lab_offline->chemical_test_glucose,
                        'chemical_test_albumin'=>$lab_offline->chemical_test_albumin,
                        'microscopic_test'=>$lab_offline->microscopic_test,
                        'microscopic_test_squamous'=>$lab_offline->microscopic_test_squamous,
                        'microscopic_test_pus'=>$lab_offline->microscopic_test_pus,
                        'microscopic_test_redblood'=>$lab_offline->microscopic_test_redblood,
                        'microscopic_test_hyaline'=>$lab_offline->microscopic_test_hyaline,
                        'microscopic_test_wbc'=>$lab_offline->microscopic_test_wbc,
                        'microscopic_test_rbc'=>$lab_offline->microscopic_test_rbc,
                        'microscopic_test_fine_granular'=>$lab_offline->microscopic_test_fine_granular,
                        'microscopic_test_coarse_granular'=>$lab_offline->microscopic_test_coarse_granular,
                        'microscopic_test_calcium_oxalate'=>$lab_offline->microscopic_test_calcium_oxalate,
                        'microscopic_test_triple_phospahte'=>$lab_offline->microscopic_test_triple_phospahte,
                        'microscopic_test_leucine_tyrosine'=>$lab_offline->microscopic_test_leucine_tyrosine,
                        'microscopic_test_ammonium_biurate'=>$lab_offline->microscopic_test_ammonium_biurate,
                        'microscopic_test_amorphous_urates'=>$lab_offline->microscopic_test_amorphous_urates,
                        'microscopic_test_amorphous_phosphates'=>$lab_offline->microscopic_test_amorphous_phosphates,
                        'microscopic_test_uricacid'=>$lab_offline->microscopic_test_uricacid,
                        'microscopic_test_mucus_thread'=>$lab_offline->microscopic_test_mucus_thread,
                        'microscopic_test_bacteria'=>$lab_offline->microscopic_test_bacteria,
                        'microscopic_test_yeast'=>$lab_offline->microscopic_test_yeast,
                        'pregnancy_test_hcg'=>$lab_offline->pregnancy_test_hcg,
                        'pregnancy_test_hcg_result'=>$lab_offline->pregnancy_test_hcg_result,
                        'order_status'=>$lab_offline->order_status,
                        'order_remarks'=>$lab_offline->order_remarks,
                        'result_remarks'=>$lab_offline->result_remarks,
                        'status'=>$lab_offline->status,
                        'created_at'=>$lab_offline->created_at,
                        'updated_at'=>$lab_offline->updated_at
                    ]); 
                } 
        }

        // syncronize laboratory_microscopy table from online to offline 
        $lab_online = DB::connection('mysql2')->table('laboratory_microscopy')->get();  
        foreach($lab_online as $lab_online){  
            $lab_online_count = DB::table('laboratory_microscopy')->where('lm_id', $lab_online->lm_id)->get();
                if(count($lab_online_count) > 0){
                    DB::table('laboratory_microscopy')->where('lm_id', $lab_online->lm_id)->update([  
                        'lm_id'=> $lab_online->lm_id, 
                        'order_id'=>$lab_online->order_id,
                        'doctor_id'=>$lab_online->doctor_id,
                        'patient_id'=>$lab_online->patient_id,
                        'laboratory_id'=>$lab_online->laboratory_id,
                        'is_viewed'=>$lab_online->is_viewed,
                        'is_processed'=>$lab_online->is_processed,
                        'is_processed_by'=>$lab_online->is_processed_by,
                        'is_processed_time_start'=>$lab_online->is_processed_time_start,
                        'is_processed_time_end'=>$lab_online->is_processed_time_end,
                        'is_pending'=>$lab_online->is_pending,
                        'is_pending_reason'=>$lab_online->is_pending_reason,
                        'is_pending_date'=>$lab_online->is_pending_date,
                        'is_pending_by'=>$lab_online->is_pending_by,
                        'spicemen'=>$lab_online->spicemen,
                        'chemical_test'=>$lab_online->chemical_test,
                        'chemical_test_color'=>$lab_online->chemical_test_color,
                        'chemical_test_transparency'=>$lab_online->chemical_test_transparency,
                        'chemical_test_ph'=>$lab_online->chemical_test_ph,
                        'chemical_test_spicific_gravity'=>$lab_online->chemical_test_spicific_gravity,
                        'chemical_test_glucose'=>$lab_online->chemical_test_glucose,
                        'chemical_test_albumin'=>$lab_online->chemical_test_albumin,
                        'microscopic_test'=>$lab_online->microscopic_test,
                        'microscopic_test_squamous'=>$lab_online->microscopic_test_squamous,
                        'microscopic_test_pus'=>$lab_online->microscopic_test_pus,
                        'microscopic_test_redblood'=>$lab_online->microscopic_test_redblood,
                        'microscopic_test_hyaline'=>$lab_online->microscopic_test_hyaline,
                        'microscopic_test_wbc'=>$lab_online->microscopic_test_wbc,
                        'microscopic_test_rbc'=>$lab_online->microscopic_test_rbc,
                        'microscopic_test_fine_granular'=>$lab_online->microscopic_test_fine_granular,
                        'microscopic_test_coarse_granular'=>$lab_online->microscopic_test_coarse_granular,
                        'microscopic_test_calcium_oxalate'=>$lab_online->microscopic_test_calcium_oxalate,
                        'microscopic_test_triple_phospahte'=>$lab_online->microscopic_test_triple_phospahte,
                        'microscopic_test_leucine_tyrosine'=>$lab_online->microscopic_test_leucine_tyrosine,
                        'microscopic_test_ammonium_biurate'=>$lab_online->microscopic_test_ammonium_biurate,
                        'microscopic_test_amorphous_urates'=>$lab_online->microscopic_test_amorphous_urates,
                        'microscopic_test_amorphous_phosphates'=>$lab_online->microscopic_test_amorphous_phosphates,
                        'microscopic_test_uricacid'=>$lab_online->microscopic_test_uricacid,
                        'microscopic_test_mucus_thread'=>$lab_online->microscopic_test_mucus_thread,
                        'microscopic_test_bacteria'=>$lab_online->microscopic_test_bacteria,
                        'microscopic_test_yeast'=>$lab_online->microscopic_test_yeast,
                        'pregnancy_test_hcg'=>$lab_online->pregnancy_test_hcg,
                        'pregnancy_test_hcg_result'=>$lab_online->pregnancy_test_hcg_result,
                        'order_status'=>$lab_online->order_status,
                        'order_remarks'=>$lab_online->order_remarks,
                        'result_remarks'=>$lab_online->result_remarks,
                        'status'=>$lab_online->status,
                        'created_at'=>$lab_online->created_at,
                        'updated_at'=>$lab_online->updated_at
                    ]); 
                }else{
                    DB::table('laboratory_microscopy')->insert([    
                        'lm_id'=> $lab_online->lm_id, 
                        'order_id'=>$lab_online->order_id,
                        'doctor_id'=>$lab_online->doctor_id,
                        'patient_id'=>$lab_online->patient_id,
                        'laboratory_id'=>$lab_online->laboratory_id,
                        'is_viewed'=>$lab_online->is_viewed,
                        'is_processed'=>$lab_online->is_processed,
                        'is_processed_by'=>$lab_online->is_processed_by,
                        'is_processed_time_start'=>$lab_online->is_processed_time_start,
                        'is_processed_time_end'=>$lab_online->is_processed_time_end,
                        'is_pending'=>$lab_online->is_pending,
                        'is_pending_reason'=>$lab_online->is_pending_reason,
                        'is_pending_date'=>$lab_online->is_pending_date,
                        'is_pending_by'=>$lab_online->is_pending_by,
                        'spicemen'=>$lab_online->spicemen,
                        'chemical_test'=>$lab_online->chemical_test,
                        'chemical_test_color'=>$lab_online->chemical_test_color,
                        'chemical_test_transparency'=>$lab_online->chemical_test_transparency,
                        'chemical_test_ph'=>$lab_online->chemical_test_ph,
                        'chemical_test_spicific_gravity'=>$lab_online->chemical_test_spicific_gravity,
                        'chemical_test_glucose'=>$lab_online->chemical_test_glucose,
                        'chemical_test_albumin'=>$lab_online->chemical_test_albumin,
                        'microscopic_test'=>$lab_online->microscopic_test,
                        'microscopic_test_squamous'=>$lab_online->microscopic_test_squamous,
                        'microscopic_test_pus'=>$lab_online->microscopic_test_pus,
                        'microscopic_test_redblood'=>$lab_online->microscopic_test_redblood,
                        'microscopic_test_hyaline'=>$lab_online->microscopic_test_hyaline,
                        'microscopic_test_wbc'=>$lab_online->microscopic_test_wbc,
                        'microscopic_test_rbc'=>$lab_online->microscopic_test_rbc,
                        'microscopic_test_fine_granular'=>$lab_online->microscopic_test_fine_granular,
                        'microscopic_test_coarse_granular'=>$lab_online->microscopic_test_coarse_granular,
                        'microscopic_test_calcium_oxalate'=>$lab_online->microscopic_test_calcium_oxalate,
                        'microscopic_test_triple_phospahte'=>$lab_online->microscopic_test_triple_phospahte,
                        'microscopic_test_leucine_tyrosine'=>$lab_online->microscopic_test_leucine_tyrosine,
                        'microscopic_test_ammonium_biurate'=>$lab_online->microscopic_test_ammonium_biurate,
                        'microscopic_test_amorphous_urates'=>$lab_online->microscopic_test_amorphous_urates,
                        'microscopic_test_amorphous_phosphates'=>$lab_online->microscopic_test_amorphous_phosphates,
                        'microscopic_test_uricacid'=>$lab_online->microscopic_test_uricacid,
                        'microscopic_test_mucus_thread'=>$lab_online->microscopic_test_mucus_thread,
                        'microscopic_test_bacteria'=>$lab_online->microscopic_test_bacteria,
                        'microscopic_test_yeast'=>$lab_online->microscopic_test_yeast,
                        'pregnancy_test_hcg'=>$lab_online->pregnancy_test_hcg,
                        'pregnancy_test_hcg_result'=>$lab_online->pregnancy_test_hcg_result,
                        'order_status'=>$lab_online->order_status,
                        'order_remarks'=>$lab_online->order_remarks,
                        'result_remarks'=>$lab_online->result_remarks,
                        'status'=>$lab_online->status,
                        'created_at'=>$lab_online->created_at,
                        'updated_at'=>$lab_online->updated_at
                    ]); 
                } 
        }   

        return true;
    } 
}